// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/pdfservice.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PDFService_GeneratePDF_FullMethodName = "/pdfservice.PDFService/GeneratePDF"
)

// PDFServiceClient is the client API for PDFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PDFServiceClient interface {
	GeneratePDF(ctx context.Context, in *PDFRequest, opts ...grpc.CallOption) (*PDFResponse, error)
}

type pDFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPDFServiceClient(cc grpc.ClientConnInterface) PDFServiceClient {
	return &pDFServiceClient{cc}
}

func (c *pDFServiceClient) GeneratePDF(ctx context.Context, in *PDFRequest, opts ...grpc.CallOption) (*PDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PDFResponse)
	err := c.cc.Invoke(ctx, PDFService_GeneratePDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PDFServiceServer is the server API for PDFService service.
// All implementations must embed UnimplementedPDFServiceServer
// for forward compatibility.
type PDFServiceServer interface {
	GeneratePDF(context.Context, *PDFRequest) (*PDFResponse, error)
	mustEmbedUnimplementedPDFServiceServer()
}

// UnimplementedPDFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPDFServiceServer struct{}

func (UnimplementedPDFServiceServer) GeneratePDF(context.Context, *PDFRequest) (*PDFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePDF not implemented")
}
func (UnimplementedPDFServiceServer) mustEmbedUnimplementedPDFServiceServer() {}
func (UnimplementedPDFServiceServer) testEmbeddedByValue()                    {}

// UnsafePDFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PDFServiceServer will
// result in compilation errors.
type UnsafePDFServiceServer interface {
	mustEmbedUnimplementedPDFServiceServer()
}

func RegisterPDFServiceServer(s grpc.ServiceRegistrar, srv PDFServiceServer) {
	// If the following call pancis, it indicates UnimplementedPDFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PDFService_ServiceDesc, srv)
}

func _PDFService_GeneratePDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDFServiceServer).GeneratePDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDFService_GeneratePDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDFServiceServer).GeneratePDF(ctx, req.(*PDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PDFService_ServiceDesc is the grpc.ServiceDesc for PDFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PDFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdfservice.PDFService",
	HandlerType: (*PDFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePDF",
			Handler:    _PDFService_GeneratePDF_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pdfservice.proto",
}
